# Built with Jekyll 3.2.0

# Setup
title:               Digital Editions of Henry James
tagline:             'Daisy Miller: A Comedy'
description:         'This edition is based on the American Osgood 1883 publication.'
url:                 'http://britaneeelizabeth.github.io'
baseurl:             '/ed'

# About/contact
author:
  name:              Britanee Smith
  url:               http://britaneeelizabeth.github.io
  email:             brit1216@tamu.edu

# Permalinks

permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Collections for texts
collections:
  texts:
    output: true

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Custom vars
version:             0.0.6

# Exclusions from the final site
exclude: [optional, vendor]


